import React from "react";

export default function FinalReport({ patient, analysis }) {
  if (!patient || !analysis) {
    return (
      <div className="panel">
        <h2>9. Final Structured Report</h2>
        <p className="small-note">Complete patient info + analysis to generate the report.</p>
      </div>
    );
  }

  const { meniscus, femur, tibia, implant_recommendation, calibration_status, mode } = analysis;

  return (
    <div className="panel">
      <h2>9. Final Structured Report</h2>

      <div className="report-block">
        <h3>Patient</h3>
        <p>ID #{patient.id} — Age {patient.age}, Sex {patient.sex}, OA status: {patient.oa_status}</p>
      </div>

      <div className="report-block">
        <h3>Calibration</h3>
        <p>
          Status: <span className={`badge ${calibration_status === "calibrated" ? "calibrated" : "uncalibrated"}`}>
            {calibration_status}
          </span> — Segmentation mode: <span className="badge mock">{mode}</span>
        </p>
      </div>

      <div className="report-block">
        <h3>Medial Meniscus Thickness</h3>
        <p>
          Anterior: {meniscus.locations_mm?.anterior ?? "—"} mm · Mid: {meniscus.locations_mm?.mid ?? "—"} mm ·
          Posterior: {meniscus.locations_mm?.posterior ?? "—"} mm · Mean: {meniscus.mean_mm ?? "—"} mm
        </p>
      </div>

      <div className="report-block">
        <h3>Femoral / Tibial Dimensions</h3>
        <p>
          Femur — Width: {femur.width_mm ?? "—"} mm, AP: {femur.ap_mm ?? "—"} mm<br />
          Tibia — Width: {tibia.width_mm ?? "—"} mm, AP: {tibia.ap_mm ?? "—"} mm
        </p>
      </div>

      <div className="report-block">
        <h3>Implant Size Recommendation</h3>
        <p>
          Femoral top match: {implant_recommendation.femoral_recommendations[0]?.size ?? "—"} (score{" "}
          {implant_recommendation.femoral_recommendations[0]?.match_score ?? "—"})<br />
          Tibial top match: {implant_recommendation.tibial_recommendations[0]?.size ?? "—"} (score{" "}
          {implant_recommendation.tibial_recommendations[0]?.match_score ?? "—"})
        </p>
      </div>

      <p className="status-msg" style={{ marginTop: 10 }}>
        <em>This report is generated by a clinical decision-support/research prototype.
        It does not constitute a diagnosis and does not replace clinician judgement.</em>
      </p>
    </div>
  );
}